language: ruby
cache: bundler
rvm:
  - 2.6.3

before_install:
  - gem update --system
  - gem install jekyll bundler kontent-jekyll

install: bundle update --jobs=3 --retry=3

script: "JEKYLL_ENV=production bundle exec jekyll build"
deploy:
  provider: pages
  local-dir: ./_site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true